/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFAZ;

import ACCESO_DATOS.controladores.*;
import ACCESO_DATOS.entidades_y_relaciones.*;
import Login.Encriptacion;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author aleja_000
 */
public class GUIJefeTaller extends javax.swing.JFrame {
    private GUIlogin login;
    private CardLayout contenedorPrincipal;
    private CardLayout contenedorOrdenCuenta;
    private CardLayout contenedorOrden;
    private CardLayout contenedorCuenta;
    private Usuario jefeLogin;
    /**
     * Creates new form GUIJefeTaller
     */
    public GUIJefeTaller(GUIlogin login2, Usuario user) {
        initComponents();
        login = login2;
        login.setVisible(false);
        jefeLogin = user;
        
        contenedorPrincipal = new CardLayout();
        contenedorOrdenCuenta = new CardLayout();
        contenedorOrden = new CardLayout();
        contenedorCuenta = new CardLayout();
    
        contenedorPrincipal.addLayoutComponent(panelJefeDeTaller, "PANEL-PRINCIPAL");
        contenedorOrdenCuenta.addLayoutComponent(panelOrden, "PANEL-ORDEN");
        contenedorOrdenCuenta.addLayoutComponent(panelCuenta, "PANEL-CUENTA");
        contenedorCuenta.addLayoutComponent(panelInformacion, "INFORMACION");
        contenedorCuenta.addLayoutComponent(panelContrasena, "CONTRASENA");
        contenedorOrden.addLayoutComponent(panelOrdenCrearOrden, "CREAR-ORDEN");
        contenedorOrden.addLayoutComponent(panelOrdenMostrarOrdenes, "MOSTRAR-ORDENES");
        
        
        panelContenedorJefe.setLayout(contenedorOrdenCuenta);
        panelContenedorJefe.add(panelOrden);
        panelContenedorJefe.add(panelCuenta);
        
        panelContenedorCuenta.setLayout(contenedorCuenta);
        panelContenedorCuenta.add(panelInformacion);
        panelContenedorCuenta.add(panelContrasena);
        
        panelContenedorOrden.setLayout(contenedorOrden);
        panelContenedorOrden.add(panelOrdenCrearOrden);
        panelContenedorOrden.add(panelOrdenMostrarOrdenes);

        ControladorVehiculo cV = new ControladorVehiculo();
        ControladorRepuesto cR = new ControladorRepuesto();
        
        ArrayList<Vehiculo> vehiculos = cV.consultarVehiculos();
        ArrayList<Repuesto> repuestos = cR.consultarRepuestos();
        
        comboBoxVehiculoOrden.removeAllItems();
        comboBoxVehiculoOrden.addItem("Seleccione un vehiculo");
        String añadir = "";
        for (int i = 0; i < vehiculos.size(); i++) {
            añadir = vehiculos.get(i).getMarca() + " | " + vehiculos.get(i).getReferencia() + " | " + vehiculos.get(i).getModelo();
            comboBoxVehiculoOrden.addItem(añadir);
        }
        
        comboBoxRepuestoVehiculo.removeAllItems();
        comboBoxRepuestoVehiculo.addItem("Seleccione uno");
        
        for (int i = 0; i < repuestos.size(); i++) {
            añadir = repuestos.get(i).getNombre();
            comboBoxRepuestoVehiculo.addItem(añadir);
        }
        
        getContentPane().setLayout(contenedorPrincipal);
        getContentPane().add(panelJefeDeTaller);
        panelJefeDeTaller.setBounds(0,0,737,522);
        setBounds(panelJefeDeTaller.getBounds());
        contenedorPrincipal.show(getContentPane(), "panelVendedor");
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJefeDeTaller = new javax.swing.JPanel();
        panelContenedorJefe = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        botonOrden = new javax.swing.JButton();
        botonLogout = new javax.swing.JButton();
        botonCuenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelOrden = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        botonGenerarVenta = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botonAyudaGeneral = new javax.swing.JButton();
        botonConsultarOrden = new javax.swing.JButton();
        panelContenedorOrden = new javax.swing.JPanel();
        panelCuenta = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        botonInformacionCuenta = new javax.swing.JButton();
        botonContrasenaCuenta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botonAyudaGeneral1 = new javax.swing.JButton();
        panelContenedorCuenta = new javax.swing.JPanel();
        panelInformacion = new javax.swing.JPanel();
        botonAyudaInformacionCuenta = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaTextoConsultarCuenta = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        panelContrasena = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        valor_antiguo = new javax.swing.JTextField();
        nuevo_valor = new javax.swing.JTextField();
        botonCambiarContraseña = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        pin_login = new javax.swing.JPasswordField();
        panelOrdenCrearOrden = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboBoxVehiculoOrden = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        comboBoxRepuestoVehiculo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        botonCrearOrden = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTextoCrearOrden = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        numero_de_orden = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cantidad_repuesto_orden = new javax.swing.JTextField();
        panelOrdenMostrarOrdenes = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaTextoConsultarOrdenes = new javax.swing.JTextArea();

        panelContenedorJefe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout panelContenedorJefeLayout = new javax.swing.GroupLayout(panelContenedorJefe);
        panelContenedorJefe.setLayout(panelContenedorJefeLayout);
        panelContenedorJefeLayout.setHorizontalGroup(
            panelContenedorJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );
        panelContenedorJefeLayout.setVerticalGroup(
            panelContenedorJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        botonOrden.setText("ORDEN DE TALLER");
        botonOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrdenActionPerformed(evt);
            }
        });

        botonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFAZ/icono-logout.png"))); // NOI18N
        botonLogout.setToolTipText("Presione aqui para salir a la ventana de Login");
        botonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLogoutActionPerformed(evt);
            }
        });

        botonCuenta.setText("CUENTA");
        botonCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuentaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ICONO-LABEL-VENDEDOR.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(botonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelJefeDeTallerLayout = new javax.swing.GroupLayout(panelJefeDeTaller);
        panelJefeDeTaller.setLayout(panelJefeDeTallerLayout);
        panelJefeDeTallerLayout.setHorizontalGroup(
            panelJefeDeTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJefeDeTallerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJefeDeTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContenedorJefe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelJefeDeTallerLayout.setVerticalGroup(
            panelJefeDeTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJefeDeTallerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelContenedorJefe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelOrden.setPreferredSize(new java.awt.Dimension(717, 388));

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonGenerarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ICONO-CREAR-ORDENTALLER.png"))); // NOI18N
        botonGenerarVenta.setToolTipText("Al hacer click en este boton, se desplegará  el menu para realizar una venta");
        botonGenerarVenta.setAutoscrolls(true);
        botonGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarVentaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonAyudaGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ICONO-AYUDA-MENULATERAL-VENDEDOR.png"))); // NOI18N
        botonAyudaGeneral.setToolTipText("Presiona este boton para obtener más ayuda");
        botonAyudaGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyudaGeneralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAyudaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAyudaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        botonConsultarOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ICONO-CONSULTAR-ORDEN.png"))); // NOI18N
        botonConsultarOrden.setToolTipText("Al hacer click en este boton, se desplegará  el menu para realizar una venta");
        botonConsultarOrden.setAutoscrolls(true);
        botonConsultarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarOrdenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonGenerarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonConsultarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(botonGenerarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonConsultarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelContenedorOrden.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelContenedorOrdenLayout = new javax.swing.GroupLayout(panelContenedorOrden);
        panelContenedorOrden.setLayout(panelContenedorOrdenLayout);
        panelContenedorOrdenLayout.setHorizontalGroup(
            panelContenedorOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        panelContenedorOrdenLayout.setVerticalGroup(
            panelContenedorOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelOrdenLayout = new javax.swing.GroupLayout(panelOrden);
        panelOrden.setLayout(panelOrdenLayout);
        panelOrdenLayout.setHorizontalGroup(
            panelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelContenedorOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelOrdenLayout.setVerticalGroup(
            panelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContenedorOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelCuenta.setPreferredSize(new java.awt.Dimension(717, 388));

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonInformacionCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ICONO-VENDEDOR-CUENTA.png"))); // NOI18N
        botonInformacionCuenta.setToolTipText("Al hacer click en este boton, se desplegará  su informacion personal");
        botonInformacionCuenta.setAutoscrolls(true);
        botonInformacionCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInformacionCuentaActionPerformed(evt);
            }
        });

        botonContrasenaCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ICONO-VENDEDOR-CONTRASENA.png"))); // NOI18N
        botonContrasenaCuenta.setToolTipText("Al hacer click en este boton, se desplegará  el menu para modificar su contraseña y usuario");
        botonContrasenaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContrasenaCuentaActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonAyudaGeneral1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ICONO-AYUDA-MENULATERAL-VENDEDOR.png"))); // NOI18N
        botonAyudaGeneral1.setToolTipText("Presiona este boton para obtener más ayuda");
        botonAyudaGeneral1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyudaGeneral1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAyudaGeneral1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAyudaGeneral1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(botonInformacionCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonContrasenaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(botonInformacionCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonContrasenaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelContenedorCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelContenedorCuentaLayout = new javax.swing.GroupLayout(panelContenedorCuenta);
        panelContenedorCuenta.setLayout(panelContenedorCuentaLayout);
        panelContenedorCuentaLayout.setHorizontalGroup(
            panelContenedorCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        panelContenedorCuentaLayout.setVerticalGroup(
            panelContenedorCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelCuentaLayout = new javax.swing.GroupLayout(panelCuenta);
        panelCuenta.setLayout(panelCuentaLayout);
        panelCuentaLayout.setHorizontalGroup(
            panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelContenedorCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCuentaLayout.setVerticalGroup(
            panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContenedorCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelInformacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInformacion.setPreferredSize(new java.awt.Dimension(586, 366));
        panelInformacion.setRequestFocusEnabled(false);
        panelInformacion.setVerifyInputWhenFocusTarget(false);

        botonAyudaInformacionCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFAZ/icono ayuda.jpg"))); // NOI18N
        botonAyudaInformacionCuenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonAyudaInformacionCuenta.setName(""); // NOI18N
        botonAyudaInformacionCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyudaInformacionCuentaActionPerformed(evt);
            }
        });

        areaTextoConsultarCuenta.setEditable(false);
        areaTextoConsultarCuenta.setColumns(20);
        areaTextoConsultarCuenta.setRows(5);
        jScrollPane3.setViewportView(areaTextoConsultarCuenta);

        jLabel14.setText("INFORMACION DE LA CUENTA DEL USUARIO");

        javax.swing.GroupLayout panelInformacionLayout = new javax.swing.GroupLayout(panelInformacion);
        panelInformacion.setLayout(panelInformacionLayout);
        panelInformacionLayout.setHorizontalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInformacionLayout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addComponent(botonAyudaInformacionCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelInformacionLayout.setVerticalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botonAyudaInformacionCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelContrasena.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelContrasena.setPreferredSize(new java.awt.Dimension(586, 366));
        panelContrasena.setRequestFocusEnabled(false);
        panelContrasena.setVerifyInputWhenFocusTarget(false);

        jLabel2.setText("CAMBIAR CONTRASEÑA");

        jLabel4.setText("PIN LOGIN:");

        jLabel12.setText("VALOR ANTIGUO: ");

        jLabel13.setText("VALOR NUEVO: ");

        botonCambiarContraseña.setText("REGISTRAR CAMBIO");
        botonCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarContraseñaActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTextField6.setEditable(false);
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField6)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelContrasenaLayout = new javax.swing.GroupLayout(panelContrasena);
        panelContrasena.setLayout(panelContrasenaLayout);
        panelContrasenaLayout.setHorizontalGroup(
            panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContrasenaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContrasenaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonCambiarContraseña))
                    .addGroup(panelContrasenaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 447, Short.MAX_VALUE))
                    .addGroup(panelContrasenaLayout.createSequentialGroup()
                        .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nuevo_valor)
                            .addComponent(valor_antiguo)
                            .addComponent(pin_login))))
                .addContainerGap())
        );
        panelContrasenaLayout.setVerticalGroup(
            panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContrasenaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pin_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(valor_antiguo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nuevo_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(botonCambiarContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelOrdenCrearOrden.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelOrdenCrearOrden.setPreferredSize(new java.awt.Dimension(586, 366));
        panelOrdenCrearOrden.setRequestFocusEnabled(false);
        panelOrdenCrearOrden.setVerifyInputWhenFocusTarget(false);

        jLabel5.setText("CREAR ORDEN DE TALLER:");

        jLabel7.setText("VEHICULO:");

        comboBoxVehiculoOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("REPUESTO PARA EL VEHICULO:");

        comboBoxRepuestoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("DESCRIPCION DE LA ORDEN:");

        botonCrearOrden.setText("AÑADIR ORDEN");
        botonCrearOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearOrdenActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        areaTextoCrearOrden.setColumns(20);
        areaTextoCrearOrden.setRows(5);
        jScrollPane2.setViewportView(areaTextoCrearOrden);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setText("NUMERO DE ORDEN: ");

        jLabel8.setText("CANTIDAD: ");

        javax.swing.GroupLayout panelOrdenCrearOrdenLayout = new javax.swing.GroupLayout(panelOrdenCrearOrden);
        panelOrdenCrearOrden.setLayout(panelOrdenCrearOrdenLayout);
        panelOrdenCrearOrdenLayout.setHorizontalGroup(
            panelOrdenCrearOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrdenCrearOrdenLayout.createSequentialGroup()
                .addGroup(panelOrdenCrearOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelOrdenCrearOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(comboBoxVehiculoOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelOrdenCrearOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrdenCrearOrdenLayout.createSequentialGroup()
                                .addGroup(panelOrdenCrearOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelOrdenCrearOrdenLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(panelOrdenCrearOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10)))
                                    .addGroup(panelOrdenCrearOrdenLayout.createSequentialGroup()
                                        .addGap(224, 224, 224)
                                        .addComponent(botonCrearOrden)))
                                .addGap(225, 225, 225))
                            .addGroup(panelOrdenCrearOrdenLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelOrdenCrearOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelOrdenCrearOrdenLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxRepuestoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cantidad_repuesto_orden))))))
                    .addGroup(panelOrdenCrearOrdenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numero_de_orden)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelOrdenCrearOrdenLayout.setVerticalGroup(
            panelOrdenCrearOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrdenCrearOrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(panelOrdenCrearOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboBoxVehiculoOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOrdenCrearOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboBoxRepuestoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cantidad_repuesto_orden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOrdenCrearOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(numero_de_orden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCrearOrden)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        panelOrdenMostrarOrdenes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelOrdenMostrarOrdenes.setPreferredSize(new java.awt.Dimension(586, 366));
        panelOrdenMostrarOrdenes.setRequestFocusEnabled(false);
        panelOrdenMostrarOrdenes.setVerifyInputWhenFocusTarget(false);

        areaTextoConsultarOrdenes.setEditable(false);
        areaTextoConsultarOrdenes.setColumns(20);
        areaTextoConsultarOrdenes.setRows(5);
        jScrollPane4.setViewportView(areaTextoConsultarOrdenes);

        javax.swing.GroupLayout panelOrdenMostrarOrdenesLayout = new javax.swing.GroupLayout(panelOrdenMostrarOrdenes);
        panelOrdenMostrarOrdenes.setLayout(panelOrdenMostrarOrdenesLayout);
        panelOrdenMostrarOrdenesLayout.setHorizontalGroup(
            panelOrdenMostrarOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrdenMostrarOrdenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelOrdenMostrarOrdenesLayout.setVerticalGroup(
            panelOrdenMostrarOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrdenMostrarOrdenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AUTOS ABC -- JEFE DE TALLER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLogoutActionPerformed
        setVisible(false);
        login.setVisible(true);
        login.reset();
    }//GEN-LAST:event_botonLogoutActionPerformed

    private void botonCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuentaActionPerformed
        contenedorOrdenCuenta.show(panelContenedorJefe, "PANEL-CUENTA");
        ControladorUsuario cUsuario = new ControladorUsuario();
        Usuario user = cUsuario.consultarUsuario(jefeLogin.getCedula());
        char genero = user.getGenero();
        int cargo = user.getCargo();
        String generoS = "";
        String cargoS = "";
        
        if (cargo == 1){
            cargoS = "GERENTE";
        }
        
        else if(cargo == 2){
            cargoS = "JEFE DE TALLER";
        }
        
        else if (cargo == 3) {
            cargoS = "VENDEDOR";
        }
        
        if (genero == 'M') {
            generoS = "MASCULINO";
        }
        
        else if (genero == 'F') {
            generoS = "FEMENINO";
        }
        
        String informacion = "INFORMACION DEL USUARIO:\n\n" +
                             "CEDULA: " + user.getCedula() + "\n" +
                             "SEDE DONDE TRABAJA: " + user.getSede() + "\n" +
                             "NOMBRE DEL USUARIO: " + user.getNombre() + "\n" +
                             "FECHA DE NACIMIENTO: " + user.getFecha() + "\n" +
                             "DIRECCION DE RESIDENCIA: " + user.getDireccion() + "\n" +
                             "GENERO: " + generoS + "\n" +
                             "EMAIL DEL USUARIO: " + user.getEmail() + "\n" +
                             "CARGO DEL USUARIO: " + cargoS + "\n" +
                             "TELEFONO DE CONTACTO: " + user.getTelefono() + "\n";
        
        areaTextoConsultarCuenta.setText(informacion);
    }//GEN-LAST:event_botonCuentaActionPerformed

    private void botonInformacionCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInformacionCuentaActionPerformed
        contenedorCuenta.show(panelContenedorCuenta,"INFORMACION");
    }//GEN-LAST:event_botonInformacionCuentaActionPerformed

    private void botonContrasenaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContrasenaCuentaActionPerformed
        contenedorCuenta.show(panelContenedorCuenta,"CONTRASENA");
    }//GEN-LAST:event_botonContrasenaCuentaActionPerformed

    private void botonAyudaInformacionCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyudaInformacionCuentaActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Aqui va un texto de ayuda");
    }//GEN-LAST:event_botonAyudaInformacionCuentaActionPerformed

    private void botonOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrdenActionPerformed
        contenedorOrdenCuenta.show(panelContenedorJefe, "PANEL-ORDEN");
    }//GEN-LAST:event_botonOrdenActionPerformed

    private void botonAyudaGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyudaGeneralActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Aqui va un texto de ayuda");        // TODO add your handling code here:
    }//GEN-LAST:event_botonAyudaGeneralActionPerformed

    private void botonAyudaGeneral1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyudaGeneral1ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Aqui va un texto de ayuda");
    }//GEN-LAST:event_botonAyudaGeneral1ActionPerformed

    private void botonGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarVentaActionPerformed
        contenedorOrden.show(panelContenedorOrden, "CREAR-ORDEN");
        
        ControladorVehiculo cV = new ControladorVehiculo();
        ControladorRepuesto cR = new ControladorRepuesto();
        
        ArrayList<Vehiculo> vehiculos = cV.consultarVehiculos();
        ArrayList<Repuesto> repuestos = cR.consultarRepuestos();
        
        comboBoxVehiculoOrden.removeAllItems();
        comboBoxVehiculoOrden.addItem("Seleccione un vehiculo");
        String añadir = "";
        for (int i = 0; i < vehiculos.size(); i++) {
            añadir = vehiculos.get(i).getMarca() + " | " + vehiculos.get(i).getReferencia() + " | " + vehiculos.get(i).getModelo();
            comboBoxVehiculoOrden.addItem(añadir);
        }
        
        comboBoxRepuestoVehiculo.removeAllItems();
        comboBoxRepuestoVehiculo.addItem("Seleccione uno");
        
        for (int i = 0; i < repuestos.size(); i++) {
            añadir = repuestos.get(i).getNombre();
            comboBoxRepuestoVehiculo.addItem(añadir);
        }
        
        
    }//GEN-LAST:event_botonGenerarVentaActionPerformed

    private void botonConsultarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarOrdenActionPerformed
        contenedorOrden.show(panelContenedorOrden, "MOSTRAR-ORDENES");
        areaTextoConsultarOrdenes.setText("");
        ControladorOrdenDeTrabajo cOrden = new ControladorOrdenDeTrabajo();
        
        ArrayList<OrdenDeTrabajo> ordenes = cOrden.consultarOrdenes();
        String informacion = "";
        
        for (int i = 0; i < ordenes.size(); i++) {
            informacion = "--------------------------------------------------------\n" +
                          "IDENTIFICACIÓN ORDEN: " + ordenes.get(i).getId_orden() + "\n" + 
                          "IDENTIFICACIÓN USUARIO: " + ordenes.get(i).getId_usuario() + "\n" +
                          "IDENTIFICACIÓN REPUESTO: " + ordenes.get(i).getId_repuesto() + "\n" +
                          "IDENTIFICACIÓN SEDE: " + ordenes.get(i).getId_sede() + "\n" +
                          "CANTIDAD REPUESTO: " + ordenes.get(i).getCantidadRepuesto() + "\n" +
                          "DESCRIPCION : " + ordenes.get(i).getDescripcion() + "\n" +
                          "--------------------------------------------------------\n";
            areaTextoConsultarOrdenes.append(informacion);
        }
    }//GEN-LAST:event_botonConsultarOrdenActionPerformed

    private void botonCrearOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearOrdenActionPerformed
        
        int response = JOptionPane.showConfirmDialog(rootPane, "¿ESTA SEGURO QUE DESEA REGISTRAR LA ORDEN?", "AutosBAC",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION){
            ControladorVehiculo cV = new ControladorVehiculo();
            ControladorRepuesto cR = new ControladorRepuesto();
            ControladorOrdenDeTrabajo cOrden = new ControladorOrdenDeTrabajo();

            ArrayList<OrdenDeTrabajo> ordenes = cOrden.consultarOrdenes();
            ArrayList<Vehiculo> vehiculos = cV.consultarVehiculos();
            ArrayList<Repuesto> repuestos = cR.consultarRepuestos();

            try {
                int cantidad = Integer.parseInt(cantidad_repuesto_orden.getText());
                int indexV = comboBoxVehiculoOrden.getSelectedIndex();
                int indexR = comboBoxRepuestoVehiculo.getSelectedIndex();
                int numero_orden = Integer.parseInt(numero_de_orden.getText());
                int cedula = jefeLogin.getCedula();
                int sede = jefeLogin.getSede();
                String descripcion = areaTextoCrearOrden.getText();
                
                int idValido = 0;

                for (int i = 0; i < ordenes.size(); i++) {
                    if (ordenes.get(i).getId_orden() == numero_orden){
                        idValido = 1;
                    }
                }

                if ((idValido == 1) | (cantidad <= 0) | (indexV == 0) | (indexR == 0) | (descripcion.equals(""))){
                    JOptionPane.showMessageDialog(rootPane, "HUBO UN ERROR EN LOS DATOS INGRESADOS, RECORDAR QUE:\n"
                                                            + "* LA CANTIDAD DEBE SER MAYOR A CERO\n"
                                                            + "* EL ID NO DEBE SER NEGATIVO NI CERO\n"
                                                            + "* LA DESCRIPCION NO DEBE ESTAR VACIA\n"
                                                            + "* DEBE SELECCIONAR UN VEHICULO\n"
                                                            + "* DEBE SELECCIONAR UN REPUESTO\n"
                                                            + "* EL NUMERO DE ORDEN DEBE SER UNICO", "AutosABC", JOptionPane.ERROR_MESSAGE);
                }
                else if ((repuestos.get(indexR - 1).getCantidad() < cantidad)){
                    JOptionPane.showMessageDialog(rootPane, "LA CANTIDAD DISPONIBLE DEL REPUESTO NO ES SUFICIENTE", "AutosABC", JOptionPane.ERROR_MESSAGE);
                }

                else {
                    int cantidadNueva = repuestos.get(indexR - 1).getCantidad() - cantidad;

                    cOrden = new ControladorOrdenDeTrabajo();

                    int result = cOrden.insertarOrden(numero_orden, cedula, vehiculos.get(indexV - 1).getVehiculo(), repuestos.get(indexR - 1).getId_repuesto(), sede, cantidad, descripcion);

                    if (result == -2) {
                        JOptionPane.showMessageDialog(rootPane, "OCURRIO UN ERROR SQL EN LA BASE DE DATOS, LLAME A SOPORTE" , "AutosABC", JOptionPane.ERROR_MESSAGE);

                    }

                    else if (result == -3) {
                        JOptionPane.showMessageDialog(rootPane, "OCURRIO UN ERROR DESCONOCIDO EN LA BASE DE DATOS, LLAME A SOPORTE" , "AutosABC", JOptionPane.ERROR_MESSAGE);
                    }

                    else {
                       cR = new ControladorRepuesto();
                        
                        int resultado = cR.cambiarCantidad(repuestos.get(indexR - 1).getId_repuesto(), cantidad);
                        JOptionPane.showMessageDialog(rootPane, "ORDEN EXPEDIDA CON EXITO" , "AutosABC", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }

            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "LA CANTIDAD Y EL NUMERO DE ORDEN TIENE QUE SER NUMERICO", "AutosABC", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "REGISTRO CANCELADO", "AutosABC", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_botonCrearOrdenActionPerformed

    private void botonCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarContraseñaActionPerformed
        try {
            char[] pinCS = pin_login.getPassword();
            String pinS = String.valueOf(pinCS);
            
            
            if (pinS.length() >= 12){
                int peso1 = 0;
                int peso2 = 0;
                int peso3 = 0;
                int peso4 = 0;
                int peso5 = 0;
                int peso6 = 0;

                char[] pinC = pin_login.getPassword();
                char [] valor = new char[2];

                valor[0] = pinC[0];
                valor[1] = pinC[1];
                peso1 = Integer.parseInt(String.valueOf(valor));

                valor[0] = pinC[2];
                valor[1] = pinC[3];
                peso2 = Integer.parseInt(String.valueOf(valor));

                valor[0] = pinC[4];
                valor[1] = pinC[5];
                peso3 = Integer.parseInt(String.valueOf(valor));

                valor[0] = pinC[6];
                valor[1] = pinC[7];
                peso4 = Integer.parseInt(String.valueOf(valor));

                valor[0] = pinC[8];
                valor[1] = pinC[9];
                peso5 = Integer.parseInt(String.valueOf(valor));

                valor[0] = pinC[10];
                valor[1] = pinC[11];
                peso6 = Integer.parseInt(String.valueOf(valor));
                
                Encriptacion encripto = new Encriptacion();
                
                ControladorUsuario cUsuario = new ControladorUsuario();
                ArrayList<Usuario> users = cUsuario.consultarLogin();

                String contraseña = "";
                for (int i = 0; i < users.size(); i++) {

                    contraseña = encripto.desencriptar(peso1, peso2, peso3, users.get(i).getContrasena());
                    
                    if ((valor_antiguo.getText().equals(contraseña)) && (users.size() > 0) && (users.get(i).getCedula() == jefeLogin.getCedula())) {

                        if(nuevo_valor.getText().equals(valor_antiguo.getText())){
                            JOptionPane.showMessageDialog(rootPane, "LA CONTRASEÑA NUEVA DEBE SER DIFERENTE A LA ACTUAL", "AutosABC", JOptionPane.ERROR_MESSAGE);
                            break;
                        }
                        else {
                            ArrayList<String> resultadoEncriptacion = encripto.encriptar(nuevo_valor.getText());
                        
                            String nuevoPin = "" + resultadoEncriptacion.get(1) + peso4 + peso5 + peso6;

                            ControladorUsuario cU = new ControladorUsuario();

                            int result = cU.cambiarPass(users.get(i).getCedula(), resultadoEncriptacion.get(0));

                            if ((result == -2) && (result == -3)){
                                JOptionPane.showMessageDialog(rootPane, "ERROR EN LA BASE DE DATOS, NO SE ACTUALIZO LA CONTRASEÑA", "AutosABC", JOptionPane.ERROR_MESSAGE);
                            }
                            else {
                                JOptionPane.showMessageDialog(rootPane, "SE HA MODIFICADO CON EXITO LA CONTRASEÑA, SU NUEVO PIN ES: " + nuevoPin, "AutosABC", JOptionPane.INFORMATION_MESSAGE);
                            }
                            break;
                        }
                    }

                    else {
                        if((i + 1) == users.size()){
                            JOptionPane.showMessageDialog(rootPane, "CONTRASEÑA ANTIGUA INCORECCTA", "AutosABC", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            }
            else {
                 JOptionPane.showMessageDialog(rootPane, "EL PIN DEBE SER UN CODIGO DE 12 NUMEROS", "AutosABC", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){           
             JOptionPane.showMessageDialog(rootPane, "EL PIN DEBE SER UN CODIGO DE 12 NUMEROS", "AutosABC", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonCambiarContraseñaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTextoConsultarCuenta;
    private javax.swing.JTextArea areaTextoConsultarOrdenes;
    private javax.swing.JTextArea areaTextoCrearOrden;
    private javax.swing.JButton botonAyudaGeneral;
    private javax.swing.JButton botonAyudaGeneral1;
    private javax.swing.JButton botonAyudaInformacionCuenta;
    private javax.swing.JButton botonCambiarContraseña;
    private javax.swing.JButton botonConsultarOrden;
    private javax.swing.JButton botonContrasenaCuenta;
    private javax.swing.JButton botonCrearOrden;
    private javax.swing.JButton botonCuenta;
    private javax.swing.JButton botonGenerarVenta;
    private javax.swing.JButton botonInformacionCuenta;
    private javax.swing.JButton botonLogout;
    private javax.swing.JButton botonOrden;
    private javax.swing.JTextField cantidad_repuesto_orden;
    private javax.swing.JComboBox<String> comboBoxRepuestoVehiculo;
    private javax.swing.JComboBox<String> comboBoxVehiculoOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField nuevo_valor;
    private javax.swing.JTextField numero_de_orden;
    private javax.swing.JPanel panelContenedorCuenta;
    private javax.swing.JPanel panelContenedorJefe;
    private javax.swing.JPanel panelContenedorOrden;
    private javax.swing.JPanel panelContrasena;
    private javax.swing.JPanel panelCuenta;
    private javax.swing.JPanel panelInformacion;
    private javax.swing.JPanel panelJefeDeTaller;
    private javax.swing.JPanel panelOrden;
    private javax.swing.JPanel panelOrdenCrearOrden;
    private javax.swing.JPanel panelOrdenMostrarOrdenes;
    private javax.swing.JPasswordField pin_login;
    private javax.swing.JTextField valor_antiguo;
    // End of variables declaration//GEN-END:variables
}
