/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFAZ;

import javax.swing.JOptionPane;
import java.awt.CardLayout;
import ACCESO_DATOS.controladores.*;
import ACCESO_DATOS.entidades_y_relaciones.*;
import Login.Encriptacion;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.event.ItemEvent;
import java.util.Arrays;


/**
 *
 * @author aleja_000
 */
public class GUIvendedor extends javax.swing.JFrame {
    
    private CardLayout contenedorPrincipal;
    private CardLayout contenedorVentaCotizacionCuenta;
    private CardLayout contenedorVentaCotizacion;
    private CardLayout contenedorCuenta;
    GUIlogin login;
    private Usuario vendedorLogin;
    private ArrayList<Vehiculo> vehiculosCotizacion;
    private ArrayList<Vehiculo> vehiculosVenta;
    
    /**
     * Creates new form GUIvendedor
     * @param login2
     * @param vendedorLogeado
     */
    public GUIvendedor(GUIlogin login2, Usuario vendedorLogeado) {
        initComponents();
        login = login2;
        vendedorLogin = vendedorLogeado;
        login.setVisible(false);
        contenedorPrincipal = new CardLayout();
        contenedorCuenta = new CardLayout();
        contenedorVentaCotizacion = new CardLayout();
        contenedorVentaCotizacionCuenta = new CardLayout();
        
        contenedorPrincipal.addLayoutComponent(panelVendedor, "panelVendedor");
        
        contenedorVentaCotizacionCuenta.addLayoutComponent(panelVenta, "VENTA/COTIZACION");
        contenedorVentaCotizacionCuenta.addLayoutComponent(panelCuenta, "CUENTA");
        
        contenedorVentaCotizacion.addLayoutComponent(panelRealizarVenta, "REALIZAR-VENTA");
        contenedorVentaCotizacion.addLayoutComponent(panelRealizarCotizacion, "REALIZAR-COTIZACION");
        contenedorVentaCotizacion.addLayoutComponent(panelOrdenMostrarVentas, "CONSULTAR-VENTAS");
        
        contenedorCuenta.addLayoutComponent(panelInformacion, "INFORMACION");
        contenedorCuenta.addLayoutComponent(panelContrasena, "CONTRASENA");
        
        panelContenedorVendedor.setLayout(contenedorVentaCotizacionCuenta);
        panelContenedorVendedor.add(panelVenta);
        panelContenedorVendedor.add(panelCuenta);
        
        panelContenedorCuenta.setLayout(contenedorCuenta);
        panelContenedorCuenta.add(panelInformacion);
        panelContenedorCuenta.add(panelContrasena);
        
        panelContenedorVenta.setLayout(contenedorVentaCotizacion);
        panelContenedorVenta.add(panelRealizarVenta);
        panelContenedorVenta.add(panelRealizarCotizacion);
        panelContenedorVenta.add(panelOrdenMostrarVentas);
        
        comboBoxVehiculoVenta.removeAllItems();
        comboBoxVehiculoVenta.addItem("Seleccione una");
      
        ControladorVehiculo cVehiculo = new ControladorVehiculo();
       
        vehiculosVenta = cVehiculo.consultarVehiculos();
       
        for (int i = 0; i < vehiculosVenta.size(); i++) {
           comboBoxVehiculoVenta.addItem(vehiculosVenta.get(i).getMarca() + " | " +
                                         vehiculosVenta.get(i).getReferencia() + " | " +
                                         vehiculosVenta.get(i).getModelo() );
        }
        
        getContentPane().setLayout(contenedorPrincipal);
        getContentPane().add(panelVendedor);
        panelVendedor.setBounds(0,0,737,522);
        setBounds(panelVendedor.getBounds());
        contenedorPrincipal.show(getContentPane(), "panelVendedor");
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVendedor = new javax.swing.JPanel();
        panelContenedorVendedor = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        botonVentaCotizacion = new javax.swing.JButton();
        botonLogout = new javax.swing.JButton();
        botonCuenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelVenta = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        botonGenerarVenta = new javax.swing.JButton();
        botonGenerarCotizacion = new javax.swing.JButton();
        botonMostrarVentas = new javax.swing.JButton();
        panelContenedorVenta = new javax.swing.JPanel();
        panelCuenta = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        botonInformacionCuenta = new javax.swing.JButton();
        botonContrasenaCuenta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botonAyudaGeneral1 = new javax.swing.JButton();
        panelContenedorCuenta = new javax.swing.JPanel();
        panelRealizarVenta = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        botonRegistrarVenta = new javax.swing.JButton();
        cedula_cliente = new javax.swing.JTextField();
        nombre_cliente = new javax.swing.JTextField();
        comboBoxVehiculoVenta = new javax.swing.JComboBox<>();
        radioBotonEfectivo = new javax.swing.JRadioButton();
        radioBotonTarjeta = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTextoVenta = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        telefono_cliente = new javax.swing.JTextField();
        panelRealizarCotizacion = new javax.swing.JPanel();
        botonRegistrarCotizacion = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        comboBoxVehiculosCotizacion = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTextoCotizacion = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        botonMostrarVehiculoCotizacion = new javax.swing.JButton();
        panelInformacion = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaTextoInformacionVendedor = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        panelContrasena = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        valor_antiguo = new javax.swing.JTextField();
        nuevo_valor = new javax.swing.JTextField();
        BotonCambioContraseña = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        pin_login = new javax.swing.JPasswordField();
        panelOrdenMostrarVentas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaTextoConsultarVentas = new javax.swing.JTextArea();
        panelAyudas = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        areaAyuda = new javax.swing.JTextArea();

        panelContenedorVendedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout panelContenedorVendedorLayout = new javax.swing.GroupLayout(panelContenedorVendedor);
        panelContenedorVendedor.setLayout(panelContenedorVendedorLayout);
        panelContenedorVendedorLayout.setHorizontalGroup(
            panelContenedorVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );
        panelContenedorVendedorLayout.setVerticalGroup(
            panelContenedorVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        botonVentaCotizacion.setText("VENDER / COTIZAR");
        botonVentaCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentaCotizacionActionPerformed(evt);
            }
        });

        botonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFAZ/icono-logout.png"))); // NOI18N
        botonLogout.setToolTipText("Presione aqui para salir a la ventana de Login");
        botonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLogoutActionPerformed(evt);
            }
        });

        botonCuenta.setText("CUENTA");
        botonCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuentaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ICONO-LABEL-VENDEDOR.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonVentaCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(botonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonVentaCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelVendedorLayout = new javax.swing.GroupLayout(panelVendedor);
        panelVendedor.setLayout(panelVendedorLayout);
        panelVendedorLayout.setHorizontalGroup(
            panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContenedorVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelVendedorLayout.setVerticalGroup(
            panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelContenedorVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelVenta.setPreferredSize(new java.awt.Dimension(717, 388));

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonGenerarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ICONO-VENDER-VEHICULO.png"))); // NOI18N
        botonGenerarVenta.setToolTipText("Al hacer click en este boton, se desplegará  el menu para realizar una venta");
        botonGenerarVenta.setAutoscrolls(true);
        botonGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarVentaActionPerformed(evt);
            }
        });

        botonGenerarCotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ICONO-COTIZAR-VEHICULO.png"))); // NOI18N
        botonGenerarCotizacion.setToolTipText("Al hacer click en este boton, se desplegará  el menu para realizar una cotizacion");
        botonGenerarCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarCotizacionActionPerformed(evt);
            }
        });

        botonMostrarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ICONO-CONSULTAR-VENTA.png"))); // NOI18N
        botonMostrarVentas.setToolTipText("Al hacer click en este boton, se desplegará  el menu para realizar una venta");
        botonMostrarVentas.setAutoscrolls(true);
        botonMostrarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGenerarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGenerarCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonMostrarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(botonGenerarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonGenerarCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonMostrarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContenedorVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelContenedorVentaLayout = new javax.swing.GroupLayout(panelContenedorVenta);
        panelContenedorVenta.setLayout(panelContenedorVentaLayout);
        panelContenedorVentaLayout.setHorizontalGroup(
            panelContenedorVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        panelContenedorVentaLayout.setVerticalGroup(
            panelContenedorVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelVentaLayout = new javax.swing.GroupLayout(panelVenta);
        panelVenta.setLayout(panelVentaLayout);
        panelVentaLayout.setHorizontalGroup(
            panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelContenedorVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelVentaLayout.setVerticalGroup(
            panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContenedorVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelCuenta.setPreferredSize(new java.awt.Dimension(717, 388));

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonInformacionCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ICONO-VENDEDOR-CUENTA.png"))); // NOI18N
        botonInformacionCuenta.setToolTipText("Al hacer click en este boton, se desplegará  su informacion personal");
        botonInformacionCuenta.setAutoscrolls(true);
        botonInformacionCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInformacionCuentaActionPerformed(evt);
            }
        });

        botonContrasenaCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ICONO-VENDEDOR-CONTRASENA.png"))); // NOI18N
        botonContrasenaCuenta.setToolTipText("Al hacer click en este boton, se desplegará  el menu para modificar su contraseña y usuario");
        botonContrasenaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContrasenaCuentaActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonAyudaGeneral1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ICONO-AYUDA-MENULATERAL-VENDEDOR.png"))); // NOI18N
        botonAyudaGeneral1.setToolTipText("Presiona este boton para obtener más ayuda");
        botonAyudaGeneral1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyudaGeneral1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAyudaGeneral1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAyudaGeneral1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonContrasenaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonInformacionCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(botonInformacionCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(botonContrasenaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelContenedorCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelContenedorCuentaLayout = new javax.swing.GroupLayout(panelContenedorCuenta);
        panelContenedorCuenta.setLayout(panelContenedorCuentaLayout);
        panelContenedorCuentaLayout.setHorizontalGroup(
            panelContenedorCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        panelContenedorCuentaLayout.setVerticalGroup(
            panelContenedorCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelCuentaLayout = new javax.swing.GroupLayout(panelCuenta);
        panelCuenta.setLayout(panelCuentaLayout);
        panelCuentaLayout.setHorizontalGroup(
            panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelContenedorCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCuentaLayout.setVerticalGroup(
            panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContenedorCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelRealizarVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelRealizarVenta.setPreferredSize(new java.awt.Dimension(586, 366));
        panelRealizarVenta.setRequestFocusEnabled(false);
        panelRealizarVenta.setVerifyInputWhenFocusTarget(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("INFORMACIÓN DE LA VENTA: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("NOMBRE COMPRADOR:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("CEDULA CLIENTE:");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("VEHICULO:");
        jLabel8.setToolTipText("");

        botonRegistrarVenta.setText("REGISTRAR VENTA");
        botonRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarVentaActionPerformed(evt);
            }
        });

        comboBoxVehiculoVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxVehiculoVenta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxVehiculoVentaItemStateChanged(evt);
            }
        });

        radioBotonEfectivo.setText("Efectivo");
        radioBotonEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBotonEfectivoActionPerformed(evt);
            }
        });

        radioBotonTarjeta.setText("Tarjeta");
        radioBotonTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBotonTarjetaActionPerformed(evt);
            }
        });

        areaTextoVenta.setEditable(false);
        areaTextoVenta.setColumns(20);
        areaTextoVenta.setRows(5);
        jScrollPane1.setViewportView(areaTextoVenta);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("FORMA DE PAGO:");
        jLabel17.setToolTipText("");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("TELEFONO COMPRADOR:");

        javax.swing.GroupLayout panelRealizarVentaLayout = new javax.swing.GroupLayout(panelRealizarVenta);
        panelRealizarVenta.setLayout(panelRealizarVentaLayout);
        panelRealizarVentaLayout.setHorizontalGroup(
            panelRealizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRealizarVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRealizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelRealizarVentaLayout.createSequentialGroup()
                        .addGroup(panelRealizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelRealizarVentaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxVehiculoVenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(radioBotonEfectivo)
                                .addGap(77, 77, 77))
                            .addGroup(panelRealizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(panelRealizarVentaLayout.createSequentialGroup()
                                    .addGroup(panelRealizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelRealizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cedula_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelRealizarVentaLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefono_cliente))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRealizarVentaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelRealizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioBotonTarjeta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonRegistrarVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelRealizarVentaLayout.setVerticalGroup(
            panelRealizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRealizarVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(panelRealizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(panelRealizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cedula_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRealizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboBoxVehiculoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioBotonEfectivo)
                    .addComponent(radioBotonTarjeta)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelRealizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(telefono_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(botonRegistrarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelRealizarCotizacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelRealizarCotizacion.setPreferredSize(new java.awt.Dimension(586, 366));
        panelRealizarCotizacion.setRequestFocusEnabled(false);
        panelRealizarCotizacion.setVerifyInputWhenFocusTarget(false);

        botonRegistrarCotizacion.setText("REGISTRAR COTIZACION");
        botonRegistrarCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarCotizacionActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("VEHICULO:");
        jLabel9.setToolTipText("");

        comboBoxVehiculosCotizacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxVehiculosCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxVehiculosCotizacionActionPerformed(evt);
            }
        });

        areaTextoCotizacion.setEditable(false);
        areaTextoCotizacion.setColumns(20);
        areaTextoCotizacion.setRows(5);
        jScrollPane2.setViewportView(areaTextoCotizacion);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("COTIZACION");
        jLabel11.setToolTipText("");

        botonMostrarVehiculoCotizacion.setText("MOSTRAR VEHICULO");
        botonMostrarVehiculoCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarVehiculoCotizacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRealizarCotizacionLayout = new javax.swing.GroupLayout(panelRealizarCotizacion);
        panelRealizarCotizacion.setLayout(panelRealizarCotizacionLayout);
        panelRealizarCotizacionLayout.setHorizontalGroup(
            panelRealizarCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRealizarCotizacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRealizarCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addGroup(panelRealizarCotizacionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonRegistrarCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRealizarCotizacionLayout.createSequentialGroup()
                        .addGroup(panelRealizarCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(panelRealizarCotizacionLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxVehiculosCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(botonMostrarVehiculoCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRealizarCotizacionLayout.setVerticalGroup(
            panelRealizarCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRealizarCotizacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addGroup(panelRealizarCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboBoxVehiculosCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMostrarVehiculoCotizacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonRegistrarCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelInformacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInformacion.setPreferredSize(new java.awt.Dimension(586, 366));
        panelInformacion.setRequestFocusEnabled(false);
        panelInformacion.setVerifyInputWhenFocusTarget(false);

        areaTextoInformacionVendedor.setEditable(false);
        areaTextoInformacionVendedor.setColumns(20);
        areaTextoInformacionVendedor.setRows(5);
        jScrollPane3.setViewportView(areaTextoInformacionVendedor);

        jLabel14.setText("INFORMACION DE LA CUENTA DEL USUARIO");

        javax.swing.GroupLayout panelInformacionLayout = new javax.swing.GroupLayout(panelInformacion);
        panelInformacion.setLayout(panelInformacionLayout);
        panelInformacionLayout.setHorizontalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 347, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelInformacionLayout.setVerticalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelContrasena.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelContrasena.setPreferredSize(new java.awt.Dimension(586, 366));
        panelContrasena.setRequestFocusEnabled(false);
        panelContrasena.setVerifyInputWhenFocusTarget(false);

        jLabel2.setText("CAMBIAR CONTRASEÑA");

        jLabel4.setText("PIN LOGIN:");

        jLabel12.setText("VALOR ANTIGUO: ");

        jLabel13.setText("VALOR NUEVO: ");

        BotonCambioContraseña.setText("REGISTRAR CAMBIO");
        BotonCambioContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCambioContraseñaActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTextField6.setEditable(false);
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField6)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelContrasenaLayout = new javax.swing.GroupLayout(panelContrasena);
        panelContrasena.setLayout(panelContrasenaLayout);
        panelContrasenaLayout.setHorizontalGroup(
            panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContrasenaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContrasenaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotonCambioContraseña))
                    .addGroup(panelContrasenaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 447, Short.MAX_VALUE))
                    .addGroup(panelContrasenaLayout.createSequentialGroup()
                        .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nuevo_valor)
                            .addComponent(valor_antiguo)
                            .addComponent(pin_login))))
                .addContainerGap())
        );
        panelContrasenaLayout.setVerticalGroup(
            panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContrasenaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pin_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(valor_antiguo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nuevo_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(BotonCambioContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelOrdenMostrarVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelOrdenMostrarVentas.setPreferredSize(new java.awt.Dimension(586, 366));
        panelOrdenMostrarVentas.setRequestFocusEnabled(false);
        panelOrdenMostrarVentas.setVerifyInputWhenFocusTarget(false);

        areaTextoConsultarVentas.setEditable(false);
        areaTextoConsultarVentas.setColumns(20);
        areaTextoConsultarVentas.setRows(5);
        jScrollPane4.setViewportView(areaTextoConsultarVentas);

        javax.swing.GroupLayout panelOrdenMostrarVentasLayout = new javax.swing.GroupLayout(panelOrdenMostrarVentas);
        panelOrdenMostrarVentas.setLayout(panelOrdenMostrarVentasLayout);
        panelOrdenMostrarVentasLayout.setHorizontalGroup(
            panelOrdenMostrarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrdenMostrarVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelOrdenMostrarVentasLayout.setVerticalGroup(
            panelOrdenMostrarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrdenMostrarVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );

        areaAyuda.setBackground(new java.awt.Color(240, 240, 240));
        areaAyuda.setColumns(20);
        areaAyuda.setRows(5);
        jScrollPane8.setViewportView(areaAyuda);

        javax.swing.GroupLayout panelAyudasLayout = new javax.swing.GroupLayout(panelAyudas);
        panelAyudas.setLayout(panelAyudasLayout);
        panelAyudasLayout.setHorizontalGroup(
            panelAyudasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAyudasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAyudasLayout.setVerticalGroup(
            panelAyudasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAyudasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AUTOS ABC -- VENDEDOR");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLogoutActionPerformed
        setVisible(false);
        login.setVisible(true);
        login.reset();
    }//GEN-LAST:event_botonLogoutActionPerformed

    private void botonVentaCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentaCotizacionActionPerformed
        contenedorVentaCotizacionCuenta.show(panelContenedorVendedor, "VENTA/COTIZACION");
        comboBoxVehiculoVenta.removeAllItems();
        comboBoxVehiculoVenta.addItem("Seleccione una");
      
        ControladorVehiculo cVehiculo = new ControladorVehiculo();
       
        vehiculosVenta = cVehiculo.consultarVehiculos();
       
        for (int i = 0; i < vehiculosVenta.size(); i++) {
           comboBoxVehiculoVenta.addItem(vehiculosVenta.get(i).getMarca() + " | " +
                                         vehiculosVenta.get(i).getReferencia() + " | " +
                                         vehiculosVenta.get(i).getModelo() );
        }
       
    }//GEN-LAST:event_botonVentaCotizacionActionPerformed

    private void botonCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuentaActionPerformed
        contenedorVentaCotizacionCuenta.show(panelContenedorVendedor, "CUENTA");
        ControladorUsuario cUsuario = new ControladorUsuario();
        Usuario user = cUsuario.consultarUsuario(vendedorLogin.getCedula());
        char genero = user.getGenero();
        int cargo = user.getCargo();
        String generoS = "";
        String cargoS = "";
        
        if (cargo == 1){
            cargoS = "GERENTE";
        }
        
        else if(cargo == 2){
            cargoS = "JEFE DE TALLER";
        }
        
        else if (cargo == 3) {
            cargoS = "VENDEDOR";
        }
        
        if (genero == 'M') {
            generoS = "MASCULINO";
        }
        
        else if (genero == 'F') {
            generoS = "FEMENINO";
        }
        
        String informacion = "INFORMACION DEL USUARIO:\n\n" +
                             "CEDULA: " + user.getCedula() + "\n" +
                             "SEDE DONDE TRABAJA: " + user.getSede() + "\n" +
                             "NOMBRE DEL USUARIO: " + user.getNombre() + "\n" +
                             "FECHA DE NACIMIENTO: " + user.getFecha() + "\n" +
                             "DIRECCION DE RESIDENCIA: " + user.getDireccion() + "\n" +
                             "GENERO: " + generoS + "\n" +
                             "EMAIL DEL USUARIO: " + user.getEmail() + "\n" +
                             "CARGO DEL USUARIO: " + cargoS + "\n" +
                             "TELEFONO DE CONTACTO: " + user.getTelefono() + "\n";
        
        areaTextoInformacionVendedor.setText(informacion);
        
    }//GEN-LAST:event_botonCuentaActionPerformed

    private void botonGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarVentaActionPerformed
        contenedorVentaCotizacion.show(panelContenedorVenta, "REALIZAR-VENTA");
         
        comboBoxVehiculoVenta.removeAllItems();
        comboBoxVehiculoVenta.addItem("Seleccione una");
      
        ControladorVehiculo cVehiculo = new ControladorVehiculo();
       
        vehiculosVenta = cVehiculo.consultarVehiculos();
       
        for (int i = 0; i < vehiculosVenta.size(); i++) {
           comboBoxVehiculoVenta.addItem(vehiculosVenta.get(i).getMarca() + " | " +
                                         vehiculosVenta.get(i).getReferencia() + " | " +
                                         vehiculosVenta.get(i).getModelo() );
        }
       
    }//GEN-LAST:event_botonGenerarVentaActionPerformed

    private void botonGenerarCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarCotizacionActionPerformed
        contenedorVentaCotizacion.show(panelContenedorVenta, "REALIZAR-COTIZACION");
        
        comboBoxVehiculosCotizacion.removeAllItems();
        comboBoxVehiculosCotizacion.addItem("Seleccione una");
        
        ControladorVehiculo cVehiculo = new ControladorVehiculo();
       
        vehiculosCotizacion = cVehiculo.consultarVehiculos();
       
        for (int i = 0; i < vehiculosCotizacion.size(); i++) {
           comboBoxVehiculosCotizacion.addItem(vehiculosCotizacion.get(i).getMarca() + " | " +
                                               vehiculosCotizacion.get(i).getReferencia() + " | " +
                                               vehiculosCotizacion.get(i).getModelo());
        }
    }//GEN-LAST:event_botonGenerarCotizacionActionPerformed

    private void botonInformacionCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInformacionCuentaActionPerformed
        contenedorCuenta.show(panelContenedorCuenta,"INFORMACION");
    }//GEN-LAST:event_botonInformacionCuentaActionPerformed

    private void botonContrasenaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContrasenaCuentaActionPerformed
        contenedorCuenta.show(panelContenedorCuenta,"CONTRASENA");
    }//GEN-LAST:event_botonContrasenaCuentaActionPerformed

    private void comboBoxVehiculosCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxVehiculosCotizacionActionPerformed
 
       
    }//GEN-LAST:event_comboBoxVehiculosCotizacionActionPerformed

    private void botonMostrarVehiculoCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarVehiculoCotizacionActionPerformed
       int index = comboBoxVehiculosCotizacion.getSelectedIndex();
       
       if (index == 0){
           JOptionPane.showMessageDialog(rootPane, "POR FAVOR SELECCIONE UN VEHICULO", "AutosABC", JOptionPane.INFORMATION_MESSAGE);
       }
       
       else {
           
           String informacionVehiculo = "";
           
           informacionVehiculo = "Marca: " + vehiculosCotizacion.get(index - 1).getMarca() + "\n" +
                                 "Referencia: " + vehiculosCotizacion.get(index - 1).getReferencia() + "\n" +
                                 "Modelo: " + vehiculosCotizacion.get(index - 1).getModelo() + "\n" +
                                 "Color: " + vehiculosCotizacion.get(index - 1).getColor() + "\n" +
                                 "Tipo: " + vehiculosCotizacion.get(index - 1).getTipo() + "\n" +
                                 "Traccion: " + vehiculosCotizacion.get(index - 1).getTraccion() + "\n" +
                                 "Precio: $ " + vehiculosCotizacion.get(index - 1).getPrecio() + " COP \n" +
                                 "IVA: $" + vehiculosCotizacion.get(index - 1).getIva() + " COP \n";
           
           areaTextoCotizacion.setText(informacionVehiculo);
           
           
       }
    }//GEN-LAST:event_botonMostrarVehiculoCotizacionActionPerformed

    private void botonRegistrarCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarCotizacionActionPerformed
        ControladorCotizacion cCotizar = new ControladorCotizacion();
        
        int index = comboBoxVehiculosCotizacion.getSelectedIndex();
        if (index > 0) {
            int result = cCotizar.insertarCotizacion(vendedorLogin.getCedula(), vehiculosCotizacion.get(index- 1).getVehiculo(), vendedorLogin.getSede());
            
            if ((result == -2 ) | (result == -3)) {
                JOptionPane.showMessageDialog(rootPane, "NO SE REGISTRO EL VEHICULO, OCURRIO UN PROBLEMA \n AL REGISTRAR EL VEHICULO EN LA BASE DE DATOS", "AutosABC", JOptionPane.ERROR_MESSAGE);
            }
            
            else {
                int response = JOptionPane.showConfirmDialog(rootPane, "SE HA REGISTRADO CON EXITO LA COTIZACION, ¿DESEA IMPRIMIR EL RECIBO?", "AutosABC", JOptionPane.INFORMATION_MESSAGE);
                if (response == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(rootPane, "POR FAVOR ESPECIFIQUE LA RUTA Y EL NOMBRE DEL ARCHIVO \n DONDE SE GUARDARÁ EL ARCHIVO DE LA COTIZACION", "AutosABC", JOptionPane.INFORMATION_MESSAGE);
                    JFileChooser dir = new JFileChooser("Cotizaciones/");
                    int option = dir.showSaveDialog(this);
                    if (option == JFileChooser.APPROVE_OPTION) {
                        File f = dir.getSelectedFile();
                        String archivo = f.toString();
                        ControladorCotizacion cCoti = new ControladorCotizacion();
                        int result2 = cCoti.consultarUltimaCotizacion();
                        try {
                            FileOutputStream archivoAguardar = new FileOutputStream(archivo + ".pdf");
                            Document doc = new Document();
                            PdfWriter.getInstance(doc, archivoAguardar);
                            doc.open();
                            Paragraph p = new Paragraph("COTIZACION DE VEHICULO\n\n", FontFactory.getFont("Arial",16,Font.ITALIC,BaseColor.RED));
                            p.setAlignment(Element.ALIGN_CENTER);
                            String informacionCotizacion = "";
                            informacionCotizacion = "Cotización Numero: " + result2 + "\n" +
                                                    "Marca: " + vehiculosCotizacion.get(index - 1).getMarca() + "\n" +
                                                    "Referencia: " + vehiculosCotizacion.get(index - 1).getReferencia() + "\n" +
                                                    "Modelo: " + vehiculosCotizacion.get(index - 1).getModelo() + "\n" +
                                                    "Color: " + vehiculosCotizacion.get(index - 1).getColor() + "\n" +
                                                    "Tipo: " + vehiculosCotizacion.get(index - 1).getTipo() + "\n" +
                                                    "Traccion: " + vehiculosCotizacion.get(index - 1).getTraccion() + "\n" +
                                                    "Precio: $ " + vehiculosCotizacion.get(index - 1).getPrecio() + " COP \n" +
                                                    "IVA: $" + vehiculosCotizacion.get(index - 1).getIva() + " COP \n" +
                                                    "Vendedor: " + vendedorLogin.getCedula()+ "\n" +
                                                    "Sede: " + vendedorLogin.getSede() + "\n\n";
                            Paragraph p2 = new Paragraph(informacionCotizacion, FontFactory.getFont("Arial",12,Font.ITALIC,BaseColor.BLACK));
                            Paragraph p3 = new Paragraph("AUTOS ABC", FontFactory.getFont("Arial",16,Font.ITALIC,BaseColor.RED));
                            p3.setAlignment(Element.ALIGN_RIGHT);
                            Image imagen = Image.getInstance("C:\\Users\\aleja_000\\Documents\\NetBeansProjects\\Proyecto-AutosABC-DS1\\src\\iconos\\logotipo.png");
                            imagen.scaleAbsolute(200, 66);
                            imagen.setAlignment(Element.ALIGN_CENTER);
                            doc.add(imagen);
                            doc.add(p);
                            doc.add(p2);
                            doc.add(p3);
                            doc.close();
                        } catch (FileNotFoundException ex) {
                            
                        }
                        catch (Exception ex) {
                            
                        }
                    }
                    
                    else {
                    
                    }
                    JOptionPane.showMessageDialog(rootPane, "RECIBO GENERADO CON EXITO", "AutosABC", JOptionPane.INFORMATION_MESSAGE);
                }
                
                else {
                
                }
            }
        }
        
        else {
            JOptionPane.showMessageDialog(rootPane, "POR FAVOR SELECCIONE UN VEHICULO", "AutosABC", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_botonRegistrarCotizacionActionPerformed

    private void comboBoxVehiculoVentaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxVehiculoVentaItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED) {
            int index = comboBoxVehiculoVenta.getSelectedIndex();

            if (index == 0){
                
            }

            else {

                String informacionVehiculo = "";

                informacionVehiculo = "Marca: " + vehiculosVenta.get(index - 1).getMarca() + "\n" +
                                      "Referencia: " + vehiculosVenta.get(index - 1).getReferencia() + "\n" +
                                      "Modelo: " + vehiculosVenta.get(index - 1).getModelo() + "\n" +
                                      "Color: " + vehiculosVenta.get(index - 1).getColor() + "\n" +
                                      "Tipo: " + vehiculosVenta.get(index - 1).getTipo() + "\n" +
                                      "Traccion: " + vehiculosVenta.get(index - 1).getTraccion() + "\n" +
                                      "Precio: $ " + vehiculosVenta.get(index - 1).getPrecio() + " COP \n" +
                                      "IVA: $" + vehiculosVenta.get(index - 1).getIva() + " COP \n";

                areaTextoVenta.setText(informacionVehiculo);

            }
        }
    }//GEN-LAST:event_comboBoxVehiculoVentaItemStateChanged

    private void radioBotonEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBotonEfectivoActionPerformed
        radioBotonTarjeta.setSelected(false);
    }//GEN-LAST:event_radioBotonEfectivoActionPerformed

    private void radioBotonTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBotonTarjetaActionPerformed
       radioBotonEfectivo.setSelected(false);
    }//GEN-LAST:event_radioBotonTarjetaActionPerformed

    private void botonRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarVentaActionPerformed
        try {
            String nombreC = nombre_cliente.getText();
            String cedulaC = Long.toString(Long.parseLong(cedula_cliente.getText()));
            String telefonoC = Long.toString(Long.parseLong(telefono_cliente.getText()));
            int cedulaV = vendedorLogin.getCedula();
            int sede = vendedorLogin.getSede();
            int index = comboBoxVehiculoVenta.getSelectedIndex();
            String pago = "";
            if(radioBotonEfectivo.isSelected()){
                pago = "EFECTIVO";
            }
            else if(radioBotonTarjeta.isSelected()){
                pago = "TARJETA";
            }
            
            if((index == 0) | (nombreC.equals("")) | (pago.equals(""))){
                JOptionPane.showMessageDialog(rootPane, "ALGUN DATO ESTA ERRONEO, RECUERDE QUE:\n"
                        + "\n1) NO DEBE HABER CAMPOS VACIOS\n2) DEBE SELECCIONAR ALGUN VEHICULO\n3) SELECCIONAR UNA FORMA DE PAGO", "AutosABC", JOptionPane.ERROR_MESSAGE);
            }
            else {
                ControladorVenta cVenta = new ControladorVenta();
                
                int result = cVenta.insertarVenta(vehiculosVenta.get(index - 1).getVehiculo(), cedulaV, sede, pago, cedulaC, nombreC, telefonoC);
                
                if ((result == -2) | (result == -3)) {
                    JOptionPane.showMessageDialog(rootPane, "ERROR EN LA BASE DE DATOS, NO SE PUDO REGISTRAR LA VENTA. \n        PORFAVOR CONTACTE CON SOPORTE", "AutosABC", JOptionPane.ERROR_MESSAGE);
                }
                
                else {
                    ControladorVehiculo cVehiculo = new ControladorVehiculo();
                    int result2 = cVehiculo.modificarEstado(vehiculosVenta.get(index - 1).getVehiculo(), "VENDIDO");
                    int response = JOptionPane.showConfirmDialog(rootPane, "SE HA REGISTRADO CON EXITO LA VENTA, ¿DESEA IMPRIMIR EL RECIBO?", "AutosABC", JOptionPane.INFORMATION_MESSAGE);
                    
                    if (response == JOptionPane.YES_OPTION) {
                        JOptionPane.showMessageDialog(rootPane, "POR FAVOR ESPECIFIQUE LA RUTA Y EL NOMBRE DEL ARCHIVO \n DONDE SE GUARDARÁ EL ARCHIVO DE LA COTIZACION", "AutosABC", JOptionPane.INFORMATION_MESSAGE);
                        JFileChooser dir = new JFileChooser("Ventas/");
                        int option = dir.showSaveDialog(this);
                        if (option == JFileChooser.APPROVE_OPTION) {
                            File f = dir.getSelectedFile();
                            String archivo = f.toString();
                            cVenta  = new ControladorVenta();
                            int result3 = cVenta.consultarUltimaVenta();
                            try {
                                FileOutputStream archivoAguardar = new FileOutputStream(archivo + ".pdf");
                                Document doc = new Document();
                                PdfWriter.getInstance(doc, archivoAguardar);
                                doc.open();
                                Paragraph p = new Paragraph("VENTA DE VEHICULO\n\n", FontFactory.getFont("Arial",16,Font.ITALIC,BaseColor.BLUE));
                                p.setAlignment(Element.ALIGN_CENTER);
                                String informacionVenta = "";
                                informacionVenta =      "Venta Numero: " + result3 + "\n" +
                                                        "Marca Vehiculo: " + vehiculosVenta.get(index - 1).getMarca() + "\n" +
                                                        "Referencia Vehiculo: " + vehiculosVenta.get(index - 1).getReferencia() + "\n" +
                                                        "Modelo Vehiculo: " + vehiculosVenta.get(index - 1).getModelo() + "\n" +
                                                        "Color Vehiculo: " + vehiculosVenta.get(index - 1).getColor() + "\n" +
                                                        "Tipo: " + vehiculosVenta.get(index - 1).getTipo() + "\n" +
                                                        "Traccion: " + vehiculosVenta.get(index - 1).getTraccion() + "\n" +
                                                        "Precio Vehiculo: $ " + vehiculosVenta.get(index - 1).getPrecio() + " COP \n" +
                                                        "IVA: $" + vehiculosVenta.get(index - 1).getIva() + " COP \n" +
                                                        "TOTAL: $" + (vehiculosVenta.get(index - 1).getIva() + vehiculosVenta.get(index - 1).getPrecio()) + " COP \n" +
                                                        "Forma de Pago: " + pago + "\n" +
                                                        "Cedula Comprador: " + cedulaC + "\n" +
                                                        "Nombre Comprador: " + nombreC + "\n" +
                                                        "Telefono Comprador: " + telefonoC + "\n" +
                                                        "Vendedor: " + vendedorLogin.getCedula()+ "\n" +
                                                        "Identificacion Sede Venta: " + vendedorLogin.getSede() + "\n\n\n\n";
                                Paragraph p2 = new Paragraph(informacionVenta, FontFactory.getFont("Arial",12,Font.ITALIC,BaseColor.BLACK));
                                Image imagen = Image.getInstance("C:\\Users\\aleja_000\\Documents\\NetBeansProjects\\Proyecto-AutosABC-DS1\\src\\iconos\\logotipo.png");
                                imagen.scaleAbsolute(200, 66);
                                imagen.setAlignment(Element.ALIGN_CENTER);
                                Image imagen2 = Image.getInstance("C:\\Users\\aleja_000\\Documents\\NetBeansProjects\\Proyecto-AutosABC-DS1\\src\\iconos\\FIRMA-VENTA.png");
                                imagen2.scaleAbsolute(200, 50);
                                imagen2.setAlignment(Element.ALIGN_RIGHT);
                                doc.add(imagen);
                                doc.add(p);
                                doc.add(p2);
                                doc.add(imagen2);
                                doc.close();
                            } catch (FileNotFoundException ex) {
                                JOptionPane.showMessageDialog(rootPane, "RUTA DEL ARCHIVO NO ENCONTRADA, NO SE GENERO EL RECIBO", "AutosABC", JOptionPane.ERROR_MESSAGE);
                            }
                            catch (Exception ex) {
                                JOptionPane.showMessageDialog(rootPane, "HA OCURRIDO UN ERROR DESCONOCIDO AL GUARDAR EL ARCHIVO", "AutosABC", JOptionPane.ERROR_MESSAGE);
                            }
                            
                            JOptionPane.showMessageDialog(rootPane, "RECIBO GENERADO CON EXITO", "AutosABC", JOptionPane.INFORMATION_MESSAGE);
                        }

                        else {

                        }
                        
                    }

                    else {

                    }
                }
            }

        }
        
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "EL TELEFONO Y LA CEDULA DEBEN SER NUMEROS", "AutosABC", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonRegistrarVentaActionPerformed

    private void botonMostrarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarVentasActionPerformed
            contenedorVentaCotizacion.show(panelContenedorVenta, "CONSULTAR-VENTAS");
        
            ControladorVenta cV = new ControladorVenta();
            ControladorVehiculo cV2 = new ControladorVehiculo();
           
            ArrayList<Venta> ventasI = cV.consultarVentas();
            ArrayList<Vehiculo> vehiculosI = cV2.consultarVehiculos2();
           
            int precio = 0;
            String informacion = "";
               for (int i = 0; i < ventasI.size(); i++){
                   informacion += "--------------------------------------------\n";
                   informacion += "IDENTIFICACION DE LA VENTA: " + ventasI.get(i).getId_venta()+ "\n";
                   informacion += "VEHICULO VENDIDO: " + ventasI.get(i).getId_vehiculo()+ "\n";
                   informacion += "CEDULA VENDEDOR: " + ventasI.get(i).getId_usuario()+ "\n";
                   informacion += "SEDE DE LA VENTA: " + ventasI.get(i).getId_sede()+ "\n";
                   informacion += "FECHA DE LA VENTA: " + ventasI.get(i).getFecha()+ "\n";
                   informacion += "FORMA DE PAGO: " + ventasI.get(i).getForma_pago()+ "\n";
                   informacion += "CEDULA COMPRADOR: " + ventasI.get(i).getCedula_cliente()+ "\n";
                   informacion += "NOMBRE COMPRADOR: " + ventasI.get(i).getNombre_cliente()+ "\n";
                   informacion += "TELEFONO COMPRADOR: " + ventasI.get(i).getTelefono_cliente()+ "\n";
                   precio = 0;
                   for (int j = 0; j < vehiculosI.size(); j++) {
                       if (ventasI.get(i).getId_vehiculo() == vehiculosI.get(j).getVehiculo()){
                           precio = vehiculosI.get(j).getPrecio() + vehiculosI.get(j).getIva();
                       }
                   }
                   informacion += "PRECIO DE LA VENTA: " + precio + "\n";
                   informacion += "--------------------------------------------\n";
               }
        areaTextoConsultarVentas.setText(informacion);

    }//GEN-LAST:event_botonMostrarVentasActionPerformed

    private void BotonCambioContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCambioContraseñaActionPerformed
        try {
            char[] pinCS = pin_login.getPassword();
            String pinS = String.valueOf(pinCS);
            
            
            if (pinS.length() >= 12){
                int peso1 = 0;
                int peso2 = 0;
                int peso3 = 0;
                int peso4 = 0;
                int peso5 = 0;
                int peso6 = 0;

                char[] pinC = pin_login.getPassword();
                char [] valor = new char[2];

                valor[0] = pinC[0];
                valor[1] = pinC[1];
                peso1 = Integer.parseInt(String.valueOf(valor));

                valor[0] = pinC[2];
                valor[1] = pinC[3];
                peso2 = Integer.parseInt(String.valueOf(valor));

                valor[0] = pinC[4];
                valor[1] = pinC[5];
                peso3 = Integer.parseInt(String.valueOf(valor));

                valor[0] = pinC[6];
                valor[1] = pinC[7];
                peso4 = Integer.parseInt(String.valueOf(valor));

                valor[0] = pinC[8];
                valor[1] = pinC[9];
                peso5 = Integer.parseInt(String.valueOf(valor));

                valor[0] = pinC[10];
                valor[1] = pinC[11];
                peso6 = Integer.parseInt(String.valueOf(valor));
                
                Encriptacion encripto = new Encriptacion();
                
                ControladorUsuario cUsuario = new ControladorUsuario();
                ArrayList<Usuario> users = cUsuario.consultarLogin();

                String contraseña = "";
                for (int i = 0; i < users.size(); i++) {

                    contraseña = encripto.desencriptar(peso1, peso2, peso3, users.get(i).getContrasena());
                    
                    if ((valor_antiguo.getText().equals(contraseña)) && (users.size() > 0) && (users.get(i).getCedula() == vendedorLogin.getCedula())) {

                        if(nuevo_valor.getText().equals(valor_antiguo.getText())){
                            JOptionPane.showMessageDialog(rootPane, "LA CONTRASEÑA NUEVA DEBE SER DIFERENTE A LA ACTUAL", "AutosABC", JOptionPane.ERROR_MESSAGE);
                            break;
                        }
                        else {
                            ArrayList<String> resultadoEncriptacion = encripto.encriptar(nuevo_valor.getText());
                        
                            String nuevoPin = "" + resultadoEncriptacion.get(1) + peso4 + peso5 + peso6;

                            ControladorUsuario cU = new ControladorUsuario();

                            int result = cU.cambiarPass(users.get(i).getCedula(), resultadoEncriptacion.get(0));

                            if ((result == -2) && (result == -3)){
                                JOptionPane.showMessageDialog(rootPane, "ERROR EN LA BASE DE DATOS, NO SE ACTUALIZO LA CONTRASEÑA", "AutosABC", JOptionPane.ERROR_MESSAGE);
                            }
                            else {
                                JOptionPane.showMessageDialog(rootPane, "SE HA MODIFICADO CON EXITO LA CONTRASEÑA, SU NUEVO PIN ES: " + nuevoPin, "AutosABC", JOptionPane.INFORMATION_MESSAGE);
                            }
                            break;
                        }
                    }

                    else {
                        if((i + 1) == users.size()){
                            JOptionPane.showMessageDialog(rootPane, "CONTRASEÑA ANTIGUA INCORECCTA", "AutosABC", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            }
            else {
                 JOptionPane.showMessageDialog(rootPane, "EL PIN DEBE SER UN CODIGO DE 12 NUMEROS", "AutosABC", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){           
             JOptionPane.showMessageDialog(rootPane, "EL PIN DEBE SER UN CODIGO DE 12 NUMEROS", "AutosABC", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonCambioContraseñaActionPerformed

    private void botonAyudaGeneral1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyudaGeneral1ActionPerformed
        String informacion  = "Para visualizar la información de la cuenta, comience por presionar el botón “Cuenta” \n"
                + "en el menú superior, al cargarse el menú del panel izquierdo presione el botón \n"
                + "“Información de la cuenta” (el que tiene una persona con una ‘i’), en ese momento se\n"
                + " cargará la información personal del usuario en el panel de la derecha.\n\n"
                + "Para modificar la información personal de su cuenta, seleccione el botón “Cuenta” del\n"
                + " menú superior, al cargarse los botones del menú izquierdo, presione el botón “Modificar información” \n"
                + "(El que tiene un par de llaves).\n" +"\n" +"\n" 
                + "Del formulario  digite su PIN, posteriormente debe digitar el valor antiguo \n"
                + "o actual y el nuevo de la contraseña. Presione el botón “Registrar Cambio” \n"
                + "ubicado en la parte inferior.";
        areaAyuda.setText(informacion);
        JOptionPane.showMessageDialog(rootPane, panelAyudas);
    }//GEN-LAST:event_botonAyudaGeneral1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCambioContraseña;
    private javax.swing.JTextArea areaAyuda;
    private javax.swing.JTextArea areaTextoConsultarVentas;
    private javax.swing.JTextArea areaTextoCotizacion;
    private javax.swing.JTextArea areaTextoInformacionVendedor;
    private javax.swing.JTextArea areaTextoVenta;
    private javax.swing.JButton botonAyudaGeneral1;
    private javax.swing.JButton botonContrasenaCuenta;
    private javax.swing.JButton botonCuenta;
    private javax.swing.JButton botonGenerarCotizacion;
    private javax.swing.JButton botonGenerarVenta;
    private javax.swing.JButton botonInformacionCuenta;
    private javax.swing.JButton botonLogout;
    private javax.swing.JButton botonMostrarVehiculoCotizacion;
    private javax.swing.JButton botonMostrarVentas;
    private javax.swing.JButton botonRegistrarCotizacion;
    private javax.swing.JButton botonRegistrarVenta;
    private javax.swing.JButton botonVentaCotizacion;
    private javax.swing.JTextField cedula_cliente;
    private javax.swing.JComboBox<String> comboBoxVehiculoVenta;
    private javax.swing.JComboBox<String> comboBoxVehiculosCotizacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField nombre_cliente;
    private javax.swing.JTextField nuevo_valor;
    private javax.swing.JPanel panelAyudas;
    private javax.swing.JPanel panelContenedorCuenta;
    private javax.swing.JPanel panelContenedorVendedor;
    private javax.swing.JPanel panelContenedorVenta;
    private javax.swing.JPanel panelContrasena;
    private javax.swing.JPanel panelCuenta;
    private javax.swing.JPanel panelInformacion;
    private javax.swing.JPanel panelOrdenMostrarVentas;
    private javax.swing.JPanel panelRealizarCotizacion;
    private javax.swing.JPanel panelRealizarVenta;
    private javax.swing.JPanel panelVendedor;
    private javax.swing.JPanel panelVenta;
    private javax.swing.JPasswordField pin_login;
    private javax.swing.JRadioButton radioBotonEfectivo;
    private javax.swing.JRadioButton radioBotonTarjeta;
    private javax.swing.JTextField telefono_cliente;
    private javax.swing.JTextField valor_antiguo;
    // End of variables declaration//GEN-END:variables
}
